/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-04-05 10:37:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myPage_005fpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Users/ICT05-17/Desktop/project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Shop/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/mypage/../common/footer.jsp", Long.valueOf(1712045918249L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1710464208852L));
    _jspx_dependants.put("/WEB-INF/views/mypage/../common/header.jsp", Long.valueOf(1712140124948L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" rel='stylesheet' />\r\n");
      out.write("<link href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" rel='stylesheet' />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>마이페이지</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	   ");
      out.write("<!--  \r\n");
      out.write(" -->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/d3367b6d2f.js\"></script>\r\n");
      out.write("    <title>헤더</title>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <header>\r\n");
      out.write("      <div class=\"inner\">\r\n");
      out.write("        <div class=\"logo\">\r\n");
      out.write("          <h1><a href=\"#\">로고</a></h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- 로그아웃 유틸 -->\r\n");
      out.write("        <div class=\"util logout_util\">\r\n");
      out.write("          <ul class=\"info\">\r\n");
      out.write("            <li><a href=\"login_page.do\">로그인</a></li>\r\n");
      out.write("            <li><a href=\"signup_page.do\">회원가입</a></li>\r\n");
      out.write("            <li><a href=\"board_page.do?u_id=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userVO.u_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">고객센터</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <form action=\"#\" class=\"h_search_form\" method=\"post\">\r\n");
      out.write("          <input type=\"text\" name=\"search\" id=\"search\" />\r\n");
      out.write("          <input type=\"submit\" value=\"검색\" />\r\n");
      out.write("        </form>\r\n");
      out.write("        <!-- 로그인 유틸 -->\r\n");
      out.write("        <div class=\"util login_util\">\r\n");
      out.write("          <ul class=\"info\">\r\n");
      out.write("            <li>이름</li>\r\n");
      out.write("            <li>보유 포인트 :</li>\r\n");
      out.write("            <li><a href=\"logout.do\">로그아웃</a></li>\r\n");
      out.write("            <li><a href=\"mypage_page.do?u_idx=1\">마이페이지</a></li>\r\n");
      out.write("            <li><a href=\"basket_page.do?u_id=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userVO.u_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">장바구니</a></li>\r\n");
      out.write("            <li><a href=\"community_page.do?u_id=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userVO.u_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">고객센터</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"gnb_wrappr\">\r\n");
      out.write("          <ul class=\"gnb\">\r\n");
      out.write("            <li class=\"category\">\r\n");
      out.write("              <a href=\"category_page.do?p_category=001\">카테고리1</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"category\">\r\n");
      out.write("              <a href=\"category_page.do?p_category=002\">카테고리2</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"category\">\r\n");
      out.write("              <a href=\"category_page.do?p_category=003\">카테고리3</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"category\">\r\n");
      out.write("              <a href=\"category_page.do?p_category=004\">카테고리4</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"category\">\r\n");
      out.write("              <a href=\"category_page.do?p_category=005\">카테고리5</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"category\">\r\n");
      out.write("              <a href=\"category_page.do?p_category=006\">카테고리6</a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<section>\r\n");
      out.write("	\r\n");
      out.write("<!--===============================================================================  -->\r\n");
      out.write("\r\n");
      out.write("		<div class=\"div\">\r\n");
      out.write("			<br>\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"orderlist_page.do?u_idx=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">주문목록</a></li>\r\n");
      out.write("				<li><a href=\"purchaselist_page.do?u_idx=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">구매목록</a></li>\r\n");
      out.write("				<li><a href=\"wishlist_page.do?u_idx=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">찜목록</a></li>\r\n");
      out.write("				<li><a href=\"#\">회원정보수정</a></li>\r\n");
      out.write("				<li><a href=\"#\">회원탈퇴</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("<!--===============================================================================  -->\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("      ");
      out.write("<!--  \r\n");
      out.write(" -->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/d3367b6d2f.js\"></script>\r\n");
      out.write("    <title>footer</title>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("      <footer>\r\n");
      out.write("        <div class=\"footer_info\">\r\n");
      out.write("          <h1>INFORMATION</h1>\r\n");
      out.write("          <br />\r\n");
      out.write("          <a href=\"#\">개인정보취급방침</a>\r\n");
      out.write("          <a href=\"#\">이용약관</a>\r\n");
      out.write("          <a href=\"#\">이메일수집거부</a>\r\n");
      out.write("          <a href=\"#\">고객센터</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr />\r\n");
      out.write("        <div class=\"footer_cominfo\">\r\n");
      out.write("          <h1>회사</h1>\r\n");
      out.write("          <br />\r\n");
      out.write("          <p>\r\n");
      out.write("            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras\r\n");
      out.write("            laoreet arcu nec massa aliquam, at pharetra tellus ultricies.\r\n");
      out.write("            Vestibulum nec velit ante. Duis sed tortor elementum nisl luctus\r\n");
      out.write("            dapibus ut ut libero. Morbi vitae gravida nisi, eu mattis augue.\r\n");
      out.write("            Donec viverra vestibulum lorem eget lobortis. Praesent id odio in\r\n");
      out.write("            urna pulvinar varius. Vestibulum sollicitudin purus a velit posuere,\r\n");
      out.write("            nec congue sem sodales. Phasellus sed enim in urna hendrerit\r\n");
      out.write("            vestibulum. Etiam id eleifend tortor. Nulla lacinia lorem eget mi\r\n");
      out.write("            vehicula, vel fringilla nulla volutpat. Integer mi enim, sagittis\r\n");
      out.write("            eget dui nec, ullamcorper volutpat dolor.\r\n");
      out.write("          </p>\r\n");
      out.write("          <br />\r\n");
      out.write("          <p>저작권 ~~~</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </footer>\r\n");
      out.write("    </section>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("	</section>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/mypage/myPage_page.jsp(10,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/resources/css/common.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/views/mypage/myPage_page.jsp(11,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/resources/css/orderlist_page.css");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }
}
